apiVersion: v1
kind: Service
metadata:
# 클러스터 내에서 서비스명은 url주소(앤드포인트)로 사용. http://my-service:포트번호
  name: my-service
  namespace: semin-ns
spec:
  type: ClusterIP
  ports:
  # port는 서비스의 port
  - port: 80
  # targetport는 pod내 컨테이너의 port(내부포트)
    targetPort: 80
  # app은 pod의 label과 일치되어야 매핑이 됨. 
  selector:
    app: my-nginx