apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: min
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest #1.22.1 latest
        imagePullPolicy: Always  # 디폴트가 Always라 안적어도 됨
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: min
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-nginx